language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    #- "3.4"

install:
    - pip install --quiet git+https://github.com/myint/cram
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install argparse; fi
    - python setup.py --quiet install

before_script:
    # Only needed on real Travis CI.
    - if [ "$TRAVIS_REPO_SLUG" != "" ]; then git config --global user.email "you@example.com"; git config --global user.name "Your Name"; fi

script:
    - cram --indent=4 test.cram
    - git-sweep --dry-run
