language: python

python:
    - "2.6"
    - "2.7"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install argparse; fi
    - pip --quiet install GitPython mock nose
    - python setup.py --quiet install

before_script:
    # Only needed on real Travis CI.
    - if [ "$TRAVIS_REPO_SLUG" != "" ]; then git config --global user.email "you@example.com"; git config --global user.name "Your Name"; fi

script:
    - python -m gitsweep.scripts.test
    - git-sweep --dry-run
